[package]
edition = "2018"
name = "archives-of-monad"
version = "0.1.0"
[dependencies]
convert_case = "0.4"
enum-display-derive = "0.1.1"
itertools = "0.10.0"
lazy_static = "1.4.0"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
meilisearch-sdk = "0.9"
futures = "0.3"