name: check

on: [push, pull_request]

jobs:
  check:
    name: Check project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Clone foundry repo
        run: |
          git clone https://gitlab.com/hooking/foundry-vtt---pathfinder-2e.git --depth 1 --branch master --single-branch foundry
      - name: Run cargo test
        run: cargo test
      - name: Run cargo check
        run: cargo check
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
      - name: Check cargo fmt
        run: cargo fmt --all -- --check
